# Generated by Django 4.2.7 on 2023-12-03 21:49

from django.db import migrations, models
import django.db.models.deletion
import landing.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Album Title')),
                ('year', models.DateField(blank=True, null=True)),
                ('picture', models.FileField(upload_to=landing.models.Album.custom_photo_path, verbose_name='Picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='picture description')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website Name')),
                ('website_slogan', tinymce.models.HTMLField(blank=True, max_length=200, null=True, verbose_name='Website Slogan')),
                ('website_favicon', models.FileField(blank=True, null=True, upload_to=landing.models.Configuration.custom_photo_path, verbose_name='Favicon')),
                ('website_logo', models.FileField(blank=True, null=True, upload_to=landing.models.Configuration.custom_photo_path, verbose_name='Logo')),
                ('website_text_loading', models.CharField(blank=True, default='So Excited ?', max_length=100, null=True, verbose_name='Website Text Load')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter Link')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Youtube Link')),
                ('dribbble_url', models.URLField(blank=True, null=True, verbose_name='Dribbble Link')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
                ('website_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('website_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('website_opening_date', models.DateTimeField(blank=True, null=True, verbose_name='Opening Date')),
                ('about_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='About Title')),
                ('about_text', tinymce.models.HTMLField(blank=True, max_length=700, null=True, verbose_name='About Text')),
                ('gallery_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gallery Title')),
                ('gallery_text', tinymce.models.HTMLField(blank=True, max_length=700, null=True, verbose_name='Gallery Text')),
                ('contact_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Title')),
                ('contact_text', tinymce.models.HTMLField(blank=True, max_length=700, null=True, verbose_name='Contact Text')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='Meta Keyword')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Subject')),
                ('content', models.TextField(verbose_name='Email Content')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.guest')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
