# Generated by Django 4.2.7 on 2023-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='guests',
        ),
        migrations.AddField(
            model_name='message',
            name='guests',
            field=models.ManyToManyField(to='landing.guest'),
        ),
    ]
